accounts/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.log_in, name="login"),
    path("logout/", views.log_out, name="logout"),
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("update/", views.update, name="update"),
    path("<int:pk>/follow/", views.follow, name="follow"),
    path("dropout/", views.dropout, name="dropout"),
    path("password/", views.password, name="password"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
  path("<int:location_pk>/", views.index, name='index'),
  path("<int:location_pk>/create/", views.create, name="create"),
  path("update/<int:review_pk>/", views.update, name="update"),
  path("delete/<int:review_pk>/", views.delete, name="delete"),
  path('like/<int:review_pk>/', views.like, name='like'),
]

triview/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("reviews/", include("reviews.urls")),
    path("accounts/", include("accounts.urls")),
    path("location/", include("location.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from imagekit.models import ProcessedImageField
from django.conf import settings
from location import models as location_models
# Create your models here.
# 여행유형 목록
Companion = (
    ('커플','커플'),
    ('가족', '가족'),
    ('친구','친구'),
    ('비즈니스','비즈니스'),
    ('솔로','솔로'),
)

# 여행일자 목록
Month_choices = (
    ('2022-11','2022년 11월'),
    ('2022-10','2022년 10월'),
    ('2022-09','2022년 09월'),
    ('2022-08','2022년 08월'),
    ('2022-07','2022년 07월'),
    ('2022-06','2022년 06월'),
    ('2022-05','2022년 05월'),
    ('2022-04','2022년 04월'),
    ('2022-03','2022년 03월'),
    ('2022-02','2022년 02월'),
    ('2022-01','2022년 01월'),
    ('2021-12','2021년 12월'),
)

# 리뷰 model class
class Review(models.Model):
  title = models.CharField(max_length=80)
  content = models.TextField(max_length=200)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  grade = models.IntegerField(
        default=3,
        validators=[MaxValueValidator(5), MinValueValidator(1)],
        verbose_name="평점",
    )
  image = ProcessedImageField(
        blank=True,
        upload_to="images/",
        format="JPEG",
        options={"quality": 80},
    )
  traveled_at = models.CharField(max_length=12, choices=Month_choices, default='2022년 11월')
  companion = models.CharField(max_length=6, choices=Companion, default='가족')
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_reviews"
    )
  location = models.ForeignKey(location_models.Location, on_delete=models.CASCADE)

reviews/forms.py
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = {
            "title",
            "traveled_at",
            "grade",
            "companion",
            "content",            
            "image",
        }

reviews/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ReviewForm
from .models import Review
from location.models import Location
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse

# Create your views here.

# 여행지-리뷰페이지
def index(request, location_pk):
    location = Location.objects.get(id=location_pk)
    reviews = Review.objects.order_by("-pk")
    grade = 0
    cnt = 0
    for review in reviews:
        if review.location == location:
            grade += review.grade
            cnt += 1
    if grade:
        grade /= cnt
    context = {
        "reviews": reviews,
        "location": location,
        "location_grade": grade,
    }

    return render(request, "reviews/index.html", context)


# 여행지-리뷰작성
@login_required
def create(request, location_pk):
    location = Location.objects.get(id=location_pk)
    if request.method == "POST":
        review_form = ReviewForm(request.POST, request.FILES)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.location = location
            review.user = request.user
            review.save()
            return redirect("reviews:index", location.pk)
    else:
        review_form = ReviewForm()
    context = {
        "review_form": review_form,
    }
    return render(request, "reviews/create.html", context)


# 여행자 리뷰 수정
@login_required
def update(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.method == "POST":
        # POST : input 값 가져와서, 검증하고, DB에 저장
        review_form = ReviewForm(request.POST, request.FILES, instance=review)
        if review_form.is_valid():
            # 유효성 검사 통과하면 저장하고, 여행리뷰 페이지로
            review_form.save()
            messages.success(request, "리뷰가 수정되었습니다.")
            return redirect("reviews:index", review.location.id)
        # 유효성 검사 통과하지 않으면 => context 부터해서 오류메시지 담긴 review_form을 랜더링
    else:
        # GET : Form을 제공
        review_form = ReviewForm(instance=review)
    context = {"review_form": review_form}
    return render(request, "reviews/update.html", context)


# 여행자 리뷰 삭제
@login_required
def delete(request, review_pk):
    review = Review.objects.get(pk=review_pk)  # 어떤 글인지
    review.delete()
    return redirect("reviews:index", review.location.id)


# 여행자 리뷰 좋아요
def like(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.user in review.like_users.all():
        review.like_users.remove(request.user)
        is_liked = False
    else:
        review.like_users.add(request.user)
        is_liked = True
    context = {
        "isLiked": is_liked,
        "likeCount": review.like_users.count(),
    }
    return JsonResponse(context)

reviews/templates/reviews/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load widget_tweaks %}
{% block content %}
  <h1 class='tit'>리뷰</h1>

  <form action='' method='POST' enctype="multipart/form-data" id="rev-form">
    {% csrf_token %}
    <label for="" class="form-label">여행 일자</label>
    {% render_field review_form.traveled_at class+="form-control"%}
    <label for="" class="form-label">여행 유형</label>
    {% render_field review_form.companion class+="form-control"%}
    <label for="" class="form-label">평점</label>
    {% render_field review_form.grade class+="form-control"%}
    <label for="" class="form-label">리뷰 제목</label>
    {% render_field review_form.title class+="form-control" placeholder=review_form.title.label %}
    <label for="" class="form-label">리뷰</label>
    {% render_field review_form.content class+="form-control" placeholder=review_form.content.label %}
    <label for="" class="form-label">리뷰 이미지</label>
    {% render_field review_form.image class+="form-control"%}

    <button type="submit" class="btnC btn-sb">리뷰 등록</button>

  </form>

{% endblock content %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}

  <div class="container review">

    <div id="carouselExampleIndicators" class="carousel slide loct-crs" data-bs-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active  data-bs-interval=" 5000""="5000" "">
          <img src="{{ location.image.url }}" class="">
        </div>
        {% for review in reviews %}
          {% if review.location == location and review.image %}
            <div class="carousel-item {% if forloop.counter == 1 %}{% endif %}" id="slide{{forloop.counter}}">
              <img src="{{ review.image.url }}" class="d-block w-100" height="700px" style="object-fit:cover">
            </div>
          {% endif %}
        {% endfor %}
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
  <div class="review_section d-flex justify-content-center align-items-center">
    <h1 class="tit">{{location.title}}</h1>
    <div class="d-flex justify-content-center loct-grd">
      <div class="bi-star{% if location_grade >= 1 %}-fill{% elif 0 < location_grade and location_grade < 1 %}-half{% endif %}"></div>
      <div class="bi-star{% if location_grade >= 2 %}-fill{% elif 1 < location_grade and location_grade < 2 %}-half{% endif %}"></div>
      <div class="bi-star{% if location_grade >= 3 %}-fill{% elif 2 < location_grade and location_grade < 3 %}-half{% endif %}"></div>
      <div class="bi-star{% if location_grade >= 4 %}-fill{% elif 3 < location_grade and location_grade < 4 %}-half{% endif %}"></div>
      <div class="bi-star{% if location_grade >= 5 %}-fill{% elif 4 < location_grade and location_grade < 5 %}-half{% endif %}"></div>
    </div>
  </div>
  <section class="review_section rev-info">
    <div class="box">
      <h3 class="sub-tit">여행지 소개</h3>
      <div class="cont">
        {% if location.desc %}
          <p>{{ location.desc }}</p>
        {% else %}
          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsum animi illo harum dolores ab quidem aut aliquid deserunt, tempora repellat dolorum maiores velit corporis? Et autem consequatur velit molestiae reprehenderit.</p>
        {% endif %}
      </div>
      <!--지도-->
      <h3 class="sub-tit">위치</h3>
      <div id="map" class="mt-3" style="width: 100%; height: 400px;"></div>
      <script async="async" defer="defer" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDHi71SmeJ6RDU4owmJ88GP9xy6dRfv7SY&callback=initMap"></script>
    </section>
    <section class="review_section rev-area">
      <div class="tit-area d-flex">
        <h3 class="sub-tit">리뷰</h3>
        {% if request.user.is_authenticated %}
          <a class="btnC" href="{% url 'reviews:create' location.pk %}">리뷰 작성
            <i class="bi bi-pencil"></i>
          </a>
        {% endif %}
      </div>
      <!--리뷰 쌓이는 곳-->
      <div class="rev">
        {% for review in reviews %}
          {% if review.location == location %}
            <div class="mb-3 box">
              <div class="rev-cont">
                <div class="d-flex justify-content-start align-items-center">
                  <div class="rev-prof">
                    {% if review.user.profile_image %}
                      <img class="prof-img" src="{{ review.user.profile_image.url }}" alt="user profile image"/>
                    {% else %}
                      <img class="prof-img" src="{% static 'img/profile_dummy.jpg' %}" alt="user profile image - dummy">
                    {% endif %}
                  </div>
                  <span>
                    <a href="{% url 'accounts:detail' review.user.pk %}">{{ review.user }}</a>
                  </span>
                </div>
                <h5 class="sub-tit">{{ review.title }}</h5>
                <p class="sub-info">
                  <span class="rev-grd-area">
                    <i class="rev-grd bi-circle{% if review.grade >= 1 %}-fill{% elif 0 < review.grade and review.grade < 1 %}-half{% endif %}"></i>
                    <i class="rev-grd bi-circle{% if review.grade >= 2 %}-fill{% elif 1 < review.grade and review.grade < 2 %}-half{% endif %}"></i>
                    <i class="rev-grd bi-circle{% if review.grade >= 3 %}-fill{% elif 2 < review.grade and review.grade < 3 %}-half{% endif %}"></i>
                    <i class="rev-grd bi-circle{% if review.grade >= 4 %}-fill{% elif 3 < review.grade and review.grade < 4 %}-half{% endif %}"></i>
                    <i class="rev-grd bi-circle{% if review.grade >= 5 %}-fill{% elif 4 < review.grade and review.grade < 5 %}-half{% endif %}"></i>
                  </span>
                  <span>
                    여행일 :{{ review.traveled_at }}
                  </span>
                </p>
                {% if review.image %}
                  <div>
                    <img src="{{ review.image.url }}" alt="{{ review.image }}" onclick="window.open(this.src)" class="rev-img"/>
                  </div>
                {% endif %}
                <p>{{ review.content }}</p>
                <p class="rev-crd text-end">{{ review.created_at|date:'Y년 m월 d일 A g시 i분' }}</p>
              </div>
              <!--좋아요 기능-->
              <div class="btn-area d-flex justify-content-between">
                <div class="like-area">
                  {% if user == review.user %}
                    <p class="btnC like-view">
                      <i class="bi bi-hand-thumbs-up-fill"></i>
                      <span class="like-count">{{review.like_users.count}}</span>
                    </p>
                  {% else %}
                    {% if request.user in review.like_users.all %}
                      <button class="btnC like-btn" data-review-id="{{review.pk}}">
                        <i class="bi bi-hand-thumbs-up-fill"></i>
                        <span class="like-count">{{review.like_users.count}}</span>
                      </button>
                    {% else %}
                      <p class="btnC btnW like-btn" data-review-id="{{review.pk}}">
                        <i class="bi bi-hand-thumbs-up like-icon"></i>
                        <span class="like-count">{{review.like_users.count}}</span>
                      </p>
                    {% endif %}
                  {% endif %}
                </div>
                <!--수정, 삭제 기능-->
                <div>
                  {% if request.user == review.user %}
                    <a class='btnC' href="{% url 'reviews:update' review.pk %}">수정</a>
                    <a class='btnC btnW' href="{% url 'reviews:delete' review.pk %}">삭제</a>
                  {% endif %}
                </div>
              </div>
            </div>
          {% endif %}
        {% endfor %}
      </div>
    </div>
  </section>

{% endblock content %}

reviews/templates/reviews/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}

  <h1 class='tit'>리뷰수정</h1>

  <form action='' method='POST' enctype="multipart/form-data" id="revud-form">
    {% csrf_token %}
    {% bootstrap_form review_form %}
    <button type="submit" class="btnC btn-sb">리뷰 수정</button>

  </form>

{% endblock content %}