location/urls.py
from django.urls import path
from . import views

app_name = "location"

urlpatterns = [
    path("create/", views.create, name="create"),
    path("", views.index, name="index"),
    path("update/<location_pk>", views.update, name="update"),
    path("delete/<location_pk>", views.delete, name="delete"),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
  path("<int:location_pk>/", views.index, name='index'),
  path("<int:location_pk>/create/", views.create, name="create"),
  path("update/<int:review_pk>/", views.update, name="update"),
  path("delete/<int:review_pk>/", views.delete, name="delete"),
  path('like/<int:review_pk>/', views.like, name='like'),
]

triview/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("reviews/", include("reviews.urls")),
    path("accounts/", include("accounts.urls")),
    path("location/", include("location.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

location/models.py
from random import choices
from django.db import models
from imagekit.models import ProcessedImageField
from django.conf import settings

# Create your models here.

CATEGORY_CHOICES = (
    ("관광지", "관광지"),
    ("음식점", "음식점"),
    ("숙소", "숙소"),
)


class Location(models.Model):
    title = models.CharField(max_length=80, verbose_name="이름")
    image = ProcessedImageField(
        upload_to="images/",
        blank=False,
        format="JPEG",
        options={"quality": 80},
        verbose_name="대표이미지",
    )
    country = models.CharField(max_length=80, verbose_name="국가")
    city = models.CharField(max_length=80, verbose_name="도시")
    category = models.CharField(
        max_length=10, choices=CATEGORY_CHOICES, default="관광지", verbose_name="카테고리"
    )
    lat = models.CharField(max_length=80, verbose_name="위도")
    lng = models.CharField(max_length=80, verbose_name="경도")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    desc = models.TextField(max_length=300, blank=True, verbose_name="장소 설명문")

location/forms.py
from django import forms
from .models import Location


class LocationForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = [
            "title",
            "country",
            "city",
            "category",
            "desc",
            "image",
            "lat",
            "lng",
        ]

location/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import LocationForm
from .models import Location
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def create(request):
    if request.method == "POST":
        location_form = LocationForm(request.POST, request.FILES)
        if location_form.is_valid():
            location = location_form.save(commit=False)
            location.user = request.user
            location.save()
            return redirect("location:index")
    else:
        location_form = LocationForm()
    context = {"location_form": location_form}
    return render(request, "location/create.html", context=context)


def index(request):
    locations = Location.objects.all()
    context = {"locations": locations}
    return render(request, "location/index.html", context)


# 장소 수정
@login_required
def update(request, location_pk):
    location = Location.objects.get(pk=location_pk)
    if request.method == "POST":
        location_form = LocationForm(request.POST, request.FILES, instance=location)
        if location_form.is_valid():
            location_form.save()
            return redirect("reviews:index", location.id)
    else:
        location_form = LocationForm(instance=location)
    context = {"location_form": location_form}
    return render(request, "location/update.html", context)


# 장소 삭제
@login_required
def delete(request, location_pk):
    location = Location.objects.get(pk=location_pk)
    location.delete()
    return redirect("location:index")

location/templates/location/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

  {% bootstrap_javascript %}
  <h1 class="tit">여행지 등록</h1>
  <form action="" method="POST" enctype="multipart/form-data" id="loc-form">
    {% csrf_token %}
    {% bootstrap_form location_form %}
    <button type="submit" class="btn-sb btnC">장소 등록</button>

  </form>

{% endblock %}

location/templates/location/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <div id="location">
    {% if request.user.is_authenticated %}
      <div class="btn-area">
        <a href="{% url 'location:create' %}" class="btnC">
          <i class="bi bi-plus-circle"></i>
          장소 등록하기</a>
      </div>
    {% endif %}
    <div class="row g-3 mt-3 justify-content-center">
      {% for location in locations %}
        <div class="col-3 box">
          <a href="{% url 'reviews:index' location.pk %}">
            <div class="box-img">
              <img src="{{ location.image.url }}">
            </div>
            <div class="box-cont">
              <h5 class="sub-tit">{{ location.title }}</h5>
              {% if request.user == location.user %}
                <div class="d-flex justify-content-end align-items-center btn-area-sm">
                  <a class='btnC' href="{% url 'location:update' location.pk %}">수정</a>
                  <a class='btnC btnW' href="{% url 'location:delete' location.pk %}">삭제</a>
                </div>
              {% endif %}
            </div>
          </a>

        </div>
      {% endfor %}
    </div>

  </div>
{% endblock %}

location/templates/location/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}

  <h1 class='tit'>여행지 수정</h1>

  <form action='' method='POST' enctype="multipart/form-data" id="revud-form">
    {% csrf_token %}
    {% bootstrap_form location_form %}
    <button type="submit" class="btnC btn-sb">장소 수정</button>

  </form>

{% endblock content %}