accounts/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.log_in, name="login"),
    path("logout/", views.log_out, name="logout"),
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("update/", views.update, name="update"),
    path("<int:pk>/follow/", views.follow, name="follow"),
    path("dropout/", views.dropout, name="dropout"),
    path("password/", views.password, name="password"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
  path("<int:location_pk>/", views.index, name='index'),
  path("<int:location_pk>/create/", views.create, name="create"),
  path("update/<int:review_pk>/", views.update, name="update"),
  path("delete/<int:review_pk>/", views.delete, name="delete"),
  path('like/<int:review_pk>/', views.like, name='like'),
]

triview/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("reviews/", include("reviews.urls")),
    path("accounts/", include("accounts.urls")),
    path("location/", include("location.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.
# 유저모델 생성
class User(AbstractUser):
    followings = models.ManyToManyField(
        "self", symmetrical=False, related_name="follower"
    )
    profile_image = ProcessedImageField(
        upload_to="images/",
        blank=True,
        format="JPEG",
        options={"quality": 80},
        processors=[ResizeToFill(150, 150)],
    )

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

# 유저폼 생성
class User(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("username", "email", "password1", "password2")


# 유저 변경 사항 폼 생성
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "first_name",
            "last_name",
            "email",
            "profile_image",
        )

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserChangeForm, User
from django.views.decorators.http import require_POST
from django.http import Http404
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.views.decorators.http import require_POST
from django.http import JsonResponse

# Create your views here.
# 회원가입
def signup(request):
    if request.method == "POST":
        form = User(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("index")
    else:
        form = User()
    context = {"form": form}
    return render(request, "accounts/signup.html", context)


# 로그인
def log_in(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = AuthenticationForm(request, data=request.POST)
            if form.is_valid():
                login(request, form.get_user())
                return redirect(request.GET.get("next") or "index")
        else:
            form = AuthenticationForm()
        context = {"form": form}
        return render(request, "accounts/login.html", context)
    else:
        return redirect("index")


# 로그아웃
@login_required
def log_out(request):
    logout(request)
    return redirect("index")


# 프로필 확인
def detail(request, pk):
    context = {
        "user": get_user_model().objects.get(pk=pk),
        "reviews": get_user_model().objects.get(pk=pk).review_set.all(),
    }
    return render(request, "accounts/detail.html", context)


# 유저 정보 변경
@login_required
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:detail", request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {"form": form}
    return render(request, "accounts/update.html", context)


# 팔로우 기능
@login_required
def follow(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)
    if request.user != get_user_model().objects.get(pk=pk):
        if request.user not in get_user_model().objects.get(pk=pk).follower.all():
            request.user.followings.add(get_user_model().objects.get(pk=pk))
            is_follow = True
        else:
            request.user.followings.remove(get_user_model().objects.get(pk=pk))
            is_follow = False
        context = {
            "isFollow": is_follow,
            "followers_count": user.follower.count(),
            "followings_count": user.followings.count(),
        }

    return JsonResponse(context)


# 탈퇴
@login_required
def dropout(request):
    if request.method == "POST":
        request.user.delete()
        logout(request)
        return redirect("location:index")
    else:
        return render(request, "accounts/dropout.html")


# 비번 변경
def password(request):
    if request.method == "POST":
        form = PasswordChangeForm(instance=request.user, data=request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect("location:index")
    else:
        form = PasswordChangeForm(request.user)
    return render(request, "accounts/password.html", {"form": form})

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div id="profile">
    <h1 class="tit">Profile</h1>
    <div class="box">
      <div class="d-flex justify-content-around">
        <div class="prof-con">
          {% if user.profile_image %}
            <img class="prof-img" src="{{ user.profile_image.url }}" alt="user profile image"/>
          {% else %}
            <img class="prof-img" src="{% static 'img/profile_dummy.jpg' %}" alt="user profile image - dummy">
          {% endif %}
        </div>
        <div>
          <h3>{{user.username }}님</h3>
          <p>{{user.email}}</p>
        </div>
        <div>
          <div class="d-flex justify-content-between  text-center">
            <div class="me-3">
              <p>팔로잉</p>
              <span id="followings-count">{{user.followings.count}}</span>
            </div>
            <div>
              <p>팔로워</p>
              <span id="followers-count">{{user.follower.count}}</span>
            </div>
          </div>
          <!--로그인 유무에 따라 팔로우 가능, 자기 자신이 팔로우 금지해둠-->
          {% if request.user != user %}
            {% if request.user.is_authenticated %}
              <div class="text-center">
                <form action="" id="follow-form" data-user-id="{{user.pk}}">
                  {% csrf_token %}
                  {% if user not in request.user.followings.all %}
                    <button type="submit" class="btnC" id="follow-btn">follow</button>
                  {% else %}
                    <button type="submit" class="btnC btnW" id="follow-btn">unfollow</button>
                  {% endif %}
                </form>
              </div>
            {% else %}
              <div>
                <a href="{% url 'accounts:login' %}" class="btnC">로그인하세요</a>
              </div>
            {% endif %}
          {% else %}
            <p class="prof-al">자기자신은 팔로잉할 수 없어요!</p>
          </div>
        {% endif %}
      </div>
      <!--자기자신만 정보 수정 링크 보이게 해둠-->
      {% if request.user.pk == user.pk %}
        <div class="prof-log d-flex justify-content-between align-items-center mt-4 px-3">
          <div>
            <!--접속여부 및 가입일-->
            <p>가입일자:
              <span>{{user.date_joined|date:'Y년 m월 d일 A '}}</span>
            </p>
            <p>마지막 로그인 시간은
              <span>{{user.last_login|date:'Y년 m월 d일 A g시 i분'}}
                입니다!</span>
            </p>
          </div>
          <div>
            <a href="{% url 'accounts:update' %}" class="btnC">정보 수정</a>
          </div>
        {% endif %}
      </div>
    </div>
    <div class="box box2">

      <!--글작성 목록 및 갯수-->
      <div class="prof-rev">
        <h4 class="sub-tit">리뷰 작성 목록</h4>
        <p>
          <span>
            {{user.username}}
          </span>
          님은 총
          <span>
            {{reviews.count}}</span>
          개의 리뷰를 쓰셨습니다!
        </p>
        <div>
          <ul class="rev-list">
            {% for review in reviews %}
              <li>
                <a href="{% url 'reviews:index' review.location.pk %}">
                  <i class="bi bi-caret-right-fill"></i>
                  {{review.location.title}}에서
                  {{review.title}}</a>
              </li>
            {% endfor %}
          </ul>
        </div>
      </div>

    </div>
    <div class="prof-del">
      <!--탈퇴 기능-->
      {% if request.user == user %}
        <a href="{% url 'accounts:dropout' %}" class="btnC btnW">회원 탈퇴</a>
      {% endif %}
    </div>

  </div>

{% endblock content %}

accounts/templates/accounts/dropout.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
  <div id="dropout">
    <div class="tit-area">
      <img src="{% static 'img/trv_logo.svg' %}" alt="trv_logo" class="logo-img">
      <h1 class='tit'>회원 탈퇴</h1>
    </div>
    <div class="box">
      <h5 class="sub-tit">회원 탈퇴를 원하시면 아래 탈퇴 버튼을 눌러주세요.</h5>
      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <button type="submit" class="btnC btnW">회원 탈퇴</button>
        <a href="{% url 'accounts:detail' user.pk %}" class="btnC btnD">취소</a>
      </form>
    </div>
  </div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% load widget_tweaks %}
{% block content %}
  <div id="login">
    <div class="tit-area">
      <img src="{% static 'img/trv_logo.svg' %}" alt="trv_logo" class="logo-img">
      <h1 class="tit">로그인</h1>
    </div>
    <form action="" method="POST" id="login-form">
      {% csrf_token %}
      <ul class="form-list">
        <li>
          <label for="username">ID</label>
          {%render_field form.username class+="userID"%}
        </li>
        <li>
          <label for="password">Password</label>
          {%render_field form.password class+="userPW"%}
        </li>
        <li>
          <button type="submit" class="btn-sb btnC">로그인</button>
        </li>
      </ul>

    </form>
  </div>
{% endblock content %}

accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block content %}
  <div id="pwupdate">
    <div class="tit-area">
      <img src="{% static 'img/trv_logo.svg' %}" alt="trv_logo" class="logo-img">
      <h1 class='tit'>비밀번호 변경</h1>
    </div>
    <form method="POST" id="pw-form">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button type="submit" class="btnC btnW">비밀번호 변경</button>
      <a href="{% url 'accounts:update'%}" class="btnC btn-sb btnD">변경 취소</a>
    </form>
  </div>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load widget_tweaks %}
{% load static %}
{% block content %}
  <div id="signup">
    <div class="tit-area">
      <img src="{% static 'img/trv_logo.svg' %}" alt="trv_logo" class="logo-img">
      <h1 class="tit">회원 가입</h1>
    </div>
    <form action="" method="POST" enctype="multipart/form-data" id="signup-form">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button type="submit" class="btn-sb btnC">가입하기</button>
    </form>
  </div>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block content %}
  <div id="update">
    <div class="tit-area">
      <img src="{% static 'img/trv_logo.svg' %}" alt="trv_logo" class="logo-img">
      <h1 class='tit'>회원 정보수정</h1>
    </div>
    <form action="" method="POST" enctype="multipart/form-data" id="update-form">
      {% csrf_token %}
      {% bootstrap_form form %}
      <div>
        <a href="{% url 'accounts:password' %}" class="btnC btnW">비밀번호 변경</a>
        <button type="submit" class="btn-sb btnC">정보 수정</button>
        <a href="{% url 'accounts:detail' user.pk %}" class="btnC btn-sb btnD">수정 취소</a>
      </div>

    </form>
  </div>

{% endblock content %}