accounts/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.log_in, name="login"),
    path("logout/", views.log_out, name="logout"),
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("update/", views.update, name="update"),
    path("<int:pk>/follow/", views.follow, name="follow"),
    path("dropout/", views.dropout, name="dropout"),
    path("password/", views.password, name="password"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

location/urls.py
from django.urls import path
from . import views

app_name = "location"

urlpatterns = [
    path("create/", views.create, name="create"),
    path("", views.index, name="index"),
    path("update/<location_pk>", views.update, name="update"),
    path("delete/<location_pk>", views.delete, name="delete"),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
  path("<int:location_pk>/", views.index, name='index'),
  path("<int:location_pk>/create/", views.create, name="create"),
  path("update/<int:review_pk>/", views.update, name="update"),
  path("delete/<int:review_pk>/", views.delete, name="delete"),
  path('like/<int:review_pk>/', views.like, name='like'),
]

triview/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("reviews/", include("reviews.urls")),
    path("accounts/", include("accounts.urls")),
    path("location/", include("location.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load django_bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'img/trv_favi.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'img/trv_favi.ico' %}" type="image/x-icon">
    {% block css %}
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
      {% bootstrap_css %}
      <link rel="stylesheet" href="{% static 'css/init.css' %}">
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock css %}
    {% block script %}
      <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
      <script defer="defer" src="{% static 'js/script.js' %}"></script>
      <script>
        var location_lat = {{ location.lat }};
        var location_lng = {{ location.lng }};
      </script>
    {% endblock script %}
    <title>TRV</title>
  </head>

  <body>
    <header>
      <nav class="py-2">
        <div class="container d-flex justify-content-between ">
          <div class="logo">
            <a href="{% url 'index' %}">
              <img src="{% static 'img/trv_logo.svg' %}" alt="trv_logo">
            </a>
          </div>
          <div>
            <ul class="nav-area d-flex justify-content-center align-items-center">
              <li class="plane-area">
                <a href="{% url 'location:index' %}">
                  <i class="bi bi-airplane-fill plane"></i>
                  여행</a>
              </li>
              {% if request.user.is_authenticated %}
                <li>
                  <a href="{% url 'accounts:detail' request.user.pk %}">{{request.user}}
                  </a>
                </li>
                <li>
                  <a href="{% url 'accounts:logout' %}">
                    로그아웃
                  </a>
                </li>
              {% else %}
                <li>
                  <a href="{% url 'accounts:signup' %}">회원가입</a>
                </li>
                <li>
                  <a href="{% url 'accounts:login' %}">로그인</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <div class="container">
        {% block indexbody %}{% endblock indexbody %}
        {% block content %}{% endblock content %}
      </div>
    </main>
    <footer>
      <div class="footer">
        <p class="cpr">2022 &copy; TRV</p>
      </div>
    </footer>
    {% bootstrap_javascript %}

  </body>

</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block indexbody %}
  <div class="container">
    <section class="idx-sect section1">
      <h2 class="tit">오늘의 여행지</h2>
      <div class="d-flex justify-content-between">
        <div class="cont-area">
          <a href="{% url 'location:index' %}">
            <img src="{% static 'img/busan.jpg' %}" alt="">
            <div class="cont-txt sub-tit">
              <p>부산</p>
            </a>
          </div>
        </div>
        <div class="cont-area">
          <a href="{% url 'location:index' %}">
            <img src="{% static 'img/osaka.jpg' %}" alt="">
            <div class="cont-txt sub-tit">
              <p>오사카</p>
            </a>
          </div>
        </div>
        <div class="cont-area">
          <a href="{% url 'location:index' %}">
            <img src="{% static 'img/berlin.jpg' %}" alt="">
            <div class="cont-txt sub-tit">
              <p>베를린</p>
            </a>
          </div>
        </div>
        <div class="cont-area">
          <a href="{% url 'location:index' %}">
            <img src="{% static 'img/paris.jpg' %}" alt="">
            <div class="cont-txt sub-tit">
              <p>파리</p>
            </a>
          </div>
        </div>
      </div>
    </section>
    <div id="carouselExampleCaptions" class="carousel slide carousel-fade" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active" data-bs-interval="5000">
          <img src="{% static 'img/banner_1.jpg' %}" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5 class="sub-tit">겨울철 인기 휴양지</h5>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit.
            </p>
          </div>
        </div>
        <div class="carousel-item" data-bs-interval="5000">
          <img src="{% static 'img/banner_2.jpg' %}" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5 class="sub-tit">싱가포르</h5>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit.
            </p>
          </div>
        </div>
        <div class="carousel-item" data-bs-interval="5000">
          <img src="{% static 'img/banner_3.jpg' %}" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5 class="sub-tit">스위스</h5>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit.
            </p>
          </div>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
    <section class="idx-sect section2 ">
      <h2 class="tit">인기 여행지</h2>
      <div class="d-flex justify-content-between">
        <div class="cont-area">
          <img src="{% static 'img/busan.jpg' %}" alt="">
          <div class="cont-txt sub-tit">
            <p>부산</p>
          </div>
        </div>
        <div class="cont-area">
          <img src="{% static 'img/osaka.jpg' %}" alt="">
          <div class="cont-txt sub-tit">
            <p>오사카</p>
          </div>
        </div>
        <div class="cont-area">
          <img src="{% static 'img/berlin.jpg' %}" alt="">
          <div class="cont-txt sub-tit">
            <p>베를린</p>
          </div>
        </div>
        <div class="cont-area">
          <img src="{% static 'img/paris.jpg' %}" alt="">
          <div class="cont-txt sub-tit">
            <p>파리</p>
          </div>
        </div>
      </div>
    </section>
    <section class="idx-sect section3">
      <h2 class="tit">추천 여행지</h2>
      <div class=" d-flex justify-content-between">
        <div class="cont-area">
          <img src="{% static 'img/busan.jpg' %}" alt="">
          <div class="cont-txt sub-tit">
            <p>부산</p>
          </div>
        </div>
        <div class="cont-area">
          <img src="{% static 'img/osaka.jpg' %}" alt="">
          <div class="cont-txt sub-tit">
            <p>오사카</p>
          </div>
        </div>
        <div class="cont-area">
          <img src="{% static 'img/berlin.jpg' %}" alt="">
          <div class="cont-txt sub-tit">
            <p>베를린</p>
          </div>
        </div>
        <div class="cont-area">
          <img src="{% static 'img/paris.jpg' %}" alt="">
          <div class="cont-txt sub-tit">
            <p>파리</p>
          </div>
        </div>
      </div>
    </section>
  </div>
{% endblock indexbody %}